# Generated by Django 5.2.3 on 2025-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('l_admin', 'Local Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
